### ISSUE TITLE
Angular Language Services

### ISSUE THREAD

**Issue by mohammedzamakhan** [marcoturi/ionic-boilerplate#34]
I started using this boilerplate, but I do not see that angular language service is working in my vscode for this project. It does work for a project that I created using angular-cli.

**Comment by mohammedzamakhan** [comment]
surprisingly it also works on projects generated using simple ionic commands 😢

**Comment by marcoturi** [comment]
It probably depends on ionic verison, just update it. Angular language service didn't work properly before angular 4.0.2

**Comment by mohammedzamakhan** [comment]
I am using "ionic-angular": "3.2.0"

**Comment by marcoturi** [comment]
I will give a look in the next days ;)

**Comment by marcoturi** [comment]
I updated the repo dependencies and in Webstorm I don't have any problem with angular language service. I'm closing for now, if you or someone else have any problems yet I will re-open.
