### ISSUE TITLE
npm run android:dev failed

### ISSUE THREAD

**Issue by Allan-Awerkin** [marcoturi/ionic-boilerplate#35]
when i run: npm run android:dev

it shows the following output on console:

> ionic2-boilerplate@0.25.0 android:dev /home/desarrollo13/proyectosionic/ejemplos/boiler2/ionic2-boilerplate
> bnr android:dev

running better-npm-run in /home/desarrollo13/proyectosionic/ejemplos/boiler2/ionic2-boilerplate
Executing script: android:dev

to be executed: ionic cordova run android --livereload 
> cordova platform add --save android
✖ Running command - failed!
[ERROR] An error occurred while running cordova platform add --save android (exit code 1):
        
        Running command: /home/desarrollo13/proyectosionic/ejemplos/boiler2/ionic2-boilerplate/hooks/before_platform_add/010_init_directories.js /home/desarrollo13/proyectosionic/ejemplos/boiler2/ionic2-boilerplate
        Using cordova-fetch for cordova-android@~6.2.2
        Error: Failed to fetch platform cordova-android@~6.2.2
        Probably this is either a connection problem, or platform spec is incorrect.
        Check your connection and platform name/version/URL.
        Failed to get absolute path to installed module

**Comment by marcoturi** [comment]
This is a problem related to cordova or your system. Be sure to have the latest cordova version installed. I have read of some problem with latest versions and android.
