### ISSUE TITLE
add a pre-build step 

### ISSUE THREAD

**Issue by millerf** [marcoturi/ionic-boilerplate#38]
Hi @marcoturi , 

First of all thanks for this project. It helped me out quite a bit to get started!
I had a feature request, and not sure how to implement it (I am new to npm and such)... 

Basically I would like to add a pre-process step to modify files based on the branch it is build on.

Let me explain: I have a configuration file for my app (app.config.ts), and I would to have different settings based on the branch (dev/stages/prod) it is on. I am not crazy about making different versions of this file on each branch, so I prefer to have a pre-build  step to take care of that.

If you are interested and give me some guidelines I could make the change and make a PR.

**Comment by marcoturi** [comment]
Hi @millerf! Can you explain why you should want to have different config based on git branch? Maybe you want different environments (i.e. dev, test, stage), but honestly i don't see any reason for having the branch affecting your project configuration.

**Comment by millerf** [comment]
YEs, different environments, that is what I mean. And I am not sure how to change those with npm

**Comment by marcoturi** [comment]
@millerf You can modify your build based on env with [better npm run](https://github.com/benoror/better-npm-run). It is already integreted in this project. Simply add npm tasks with different env vars based on your need. Take a look to the package.json file of this repo.

**Comment by millerf** [comment]
Thanks for the tip!
