### ISSUE TITLE
Is it possible to start a project with ionic 2 and not 3? 

### ISSUE THREAD

**Issue by sunsgs** [marcoturi/ionic-boilerplate#41]
Please tell me 'YES' :)

**Comment by marcoturi** [comment]
Yes, you have two ways:
- Open package.json and edit dependecies (suggested method).
- Go back in commit history of pakage.json and copy it.

**Comment by sunsgs** [comment]
which dependencie do i need to change? 
it works also for ionic v1?

thanks
